apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: shopsy
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP