apiVersion: v1
kind: Secret
metadata:
  name: shopsy-secret
  namespace: shopsy
type: Opaque
stringData:
  db-username: shopsy
  db-password: shopsy
  db-name: shopsy
  jwt-secret: 01234567890123456789012345678901
