apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopsy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: asia-south1-docker.pkg.dev/shopsy-nagp-2025/shopsy/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/shopsy
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shopsy-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopsy-secret
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
