apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: shopsy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: asia-south1-docker.pkg.dev/shopsy-nagp-2025/shopsy/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/shopsy
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shopsy-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopsy-secret
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopsy-secret
                  key: jwt-secret
            - name: APP_JWT_EXPIRATION_MS
              value: "3600000"
