apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: shopsy
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
