apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: shopsy
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
